apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /data
        while true; do
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Hello from Kubernetes Pod" >> /data/message.txt
          sleep 1
        done
    volumeMounts:
    - name: data-volume
      mountPath: /data

  volumes:
  - name: data-volume
    emptyDir: {}
