services:
    web:
      build: ./app
      ports:
        - "5000:5000"
      networks:
        - app-network
      labels:
        project: day34
        

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: appdb
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - app-network
      labels:
        project: day34

    redis:
      image: redis
      networks:
        - app-network
      labels:
        project: day34

volumes:
  postgres-data:

networks:
  app-network:
