apiVersion: v1
kind: Pod
metadata:
  name: live-pod
spec:
  containers:
  - name: live-pod
    image: busybox:latest
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: live-config
        mountPath: /etc/nginx/live-config.d
  volumes:
    - name: live-config
      configMap:
        name: live-config
