apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: my-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-sql
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "50m"
              memory: "256Gi"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: my-mount
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: my-mount
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

