apiVersion: v1
kind: Pod
metadata:
  name: startup-probe
spec:
  containers:
  - name: startup-probe
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
      - sleep 20
        touch /tmp/started
        sleep 3600
    startupProbe:
      exec:
        command:
          - cat
          - /tmp/started
      periodSeconds: 5
      failureThreshold: 12
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/started
          #      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 3
