apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-pod
        image: registry.k8s.io/hpa-example
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 80
