apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: my-app
  serviceName: "headless-svc"
  replicas: 3 
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: myvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 100Mi
